version: "3.9"

services:
  unihub-web:
    build:
      context: ./src/web
      dockerfile: Dockerfile
    container_name: unihub-web
    ports:
      - "3000:3000"
    depends_on:
      - unihub-backend

  unihub-backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: unihub-backend
    ports:
      - "8080:8080"
    env_file:
      - ./src/backend/.env
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: unihub-redis
    ports:
      - "6379:6379"

  # minio:
  #   image: minio/minio:latest
  #   container_name: unihub-minio
  #   command: server /data --console-address ":9001"
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   environment:
  #     MINIO_ROOT_USER: minio
  #     MINIO_ROOT_PASSWORD: minio_password
  #   volumes:
  #     - minio_data:/data

volumes:
  minio_data:
